#! /usr/local/bin/python3

import sys
try:
    import html2text # html 转 markdown 的工具包
except Exception as e:
    print('缺少 html2text 模块，请使用 "pip install html2text" 进行安装')
    sys.exit(-1)

print(123)
args = sys.argv[:]

filename = args[1] # 获取文件名称

txt = ''
with open(filename) as file:
    txt = file.read()

with open(filename+'.md', 'w+') as file: # 创建新文件并且追加
    md_txt = html2text.html2text(txt)
    file.write(md_txt)

